### ISSUE TITLE
Feature Request: Kotlin support

### ISSUE THREAD

**Issue by jmfayard** [chrisgrieser/alfred-docs-searches#4]
### Feature Requested

`kotlin <search>` keyword leading to the corresponding result at https://kotlinlang.org/

Exemple: 

`kotlin multiplatform`
👉🏻 [Kotlin Multiplatform | Kotlin Documentation](https://kotlinlang.org/docs/multiplatform.html#multiplatform-libraries)
👉🏻 [Multiplatform Gradle DSL reference | Kotlin Documentation](https://kotlinlang.org/docs/multiplatform-dsl-reference.html)
👉🏻 [Publishing multiplatform libraries | Kotlin Documentation](https://kotlinlang.org/docs/multiplatform-publish-lib.html)

### Relevant Screenshot

![2023-12-29 kotlin multiplatform](https://github.com/chrisgrieser/alfred-docs-searches/assets/459464/a061cfb3-91da-495c-ac9d-094441117344)

### Checklist

- [X] The feature would be useful to more users than just me.

Thanks for this amazingly useful plugin, I have no idea how it works, but happy to contribute once I understand how that could be done.

**Comment by chrisgrieser** [comment]
> Thanks for this amazingly useful plugin, I have no idea how it works, but happy to contribute once I understand how that could be done.

You're welcome! It's not too complex, most of the work is done by Alfred. What this workflow does is to look through some sort of index of documentation sites (e.g. a `/docs` folder in a GitHub repo) and re-format the list of files into [a format Alfred understands](https://www.alfredapp.com/help/workflows/inputs/script-filter/json/).

In most cases, this is less than 40 lines of code per documentation site. See for example the script [fetching `eslint` docs sites from the `eslint` repo](https://github.com/chrisgrieser/alfred-docs-searches/blob/main/scripts/eslint-docs-search.js). Those scripts do not need to be written in JavaScript, any language that outputs stringified JSON works.

So if you want to contribute more documentation searches, you are welcome! Since I am not familiar with Kotlin, I'd refrain from creating the docs-search for it myself anyway.

**Comment by chrisgrieser** [comment]
With version 2.0, this workflow has been overhauled to include all devdocs, meaning Kotlin is now supported.

https://github.com/chrisgrieser/alfred-docs-searches/releases/download/2.0.0/alfred-docs-searches.alfredworkflow
