### ISSUE TITLE
Feature Request: Config for DevDocs versions

### ISSUE THREAD

**Issue by rkoval** [chrisgrieser/alfred-docs-searches#9]
Hello there! This workflow is amazing! I'm really enjoying the productivity boost I get from it.

One feature request though: can we get config options for specific versions within DevDocs? For example, this workflow seems to provide the `node` configuration value for nodejs, which defaults to [the latest nodejs version](https://devdocs.io/node/) in DevDocs. However, this is not what I want; I want to target an older LTS version that I use for work ([example](https://devdocs.io/node~16_lts/)). Would it be easy to be able to select explicit versions in DevDocs for supported docs?

Thanks so much for your hard work here!!

**Comment by chrisgrieser** [comment]
Hi, thanks for the kind words!

On a purely technical level, pinning a specific version is not too hard. However, it's tricky to make the version selection work nicely with the Alfred UI (the current dropdown in Alfred for this workflow is already a bit much), and also with the fact that a good part of this Alfred workflow is auto-generating itself to keep up with devdoc version changes…

I do not have the time right now to implement this in a very user-friendly way, but since I can see the need for using specific versions, I added a very simple, quick and dirty solution, which requires a bit of manual work on the user side: https://github.com/chrisgrieser/alfred-docs-searches?tab=readme-ov-file#pinning-specific-versions

Update will be available in 2–3 days in the Alfred gallery, or you can update manually now:
https://github.com/chrisgrieser/alfred-docs-searches/releases/download/2.7.0/alfred-docs-searches.alfredworkflow

Hope this works for now!

**Comment by chrisgrieser** [comment]
Slightly simplified the setup in 2.7.4, see the updated instructiosn ins the README

https://github.com/chrisgrieser/alfred-docs-searches/releases/download/2.7.4/alfred-docs-searches.alfredworkflow
